//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalendarDll.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class addresstype
    {
        public int AddressTypeID { get; set; }
        public int LanguageID { get; set; }
        public int CountryID { get; set; }
        public string AddressType1 { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool Active { get; set; }
        public bool UniquePerUser { get; set; }
        public bool Selectable { get; set; }
    }
}
