//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalendarDll.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarReccurrenceFrequency
    {
        public int ID { get; set; }
        public Nullable<int> CalendarReccursiveID { get; set; }
        public Nullable<bool> ByDay { get; set; }
        public Nullable<bool> ByHour { get; set; }
        public Nullable<bool> ByMinute { get; set; }
        public Nullable<bool> ByMonth { get; set; }
        public Nullable<bool> ByMonthDay { get; set; }
        public Nullable<bool> BySecond { get; set; }
        public Nullable<bool> BySetPosition { get; set; }
        public Nullable<bool> ByWeekNo { get; set; }
        public Nullable<bool> ByYearDay { get; set; }
        public Nullable<int> ExtraValue { get; set; }
        public Nullable<int> FrequencyDay { get; set; }
        public Nullable<int> DayOfWeek { get; set; }
    
        public virtual CalendarReccurrence CalendarReccurrence { get; set; }
    }
}
