//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalendarDll.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarAvailabilityType
    {
        public CalendarAvailabilityType()
        {
            this.CalendarEvents = new HashSet<CalendarEvents>();
        }
    
        public int CalendarAvailabilityTypeID { get; set; }
        public int LanguageID { get; set; }
        public int CountryID { get; set; }
        public string CalendarAvailabilityTypeName { get; set; }
        public string CalendarAvailabilityTypeDescription { get; set; }
        public string SelectableAs { get; set; }
    
        public virtual ICollection<CalendarEvents> CalendarEvents { get; set; }
    }
}
