//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalendarDll.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarEventType
    {
        public CalendarEventType()
        {
            this.CalendarEvents = new HashSet<CalendarEvents>();
        }
    
        public int EventTypeId { get; set; }
        public string EventType { get; set; }
        public string Description { get; set; }
        public string DisplayName { get; set; }
    
        public virtual ICollection<CalendarEvents> CalendarEvents { get; set; }
    }
}
