//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalendarDll.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarEventsContacts
    {
        public int Id { get; set; }
        public int IdEvent { get; set; }
        public string Contact { get; set; }
    
        public virtual CalendarEvents CalendarEvents { get; set; }
    }
}
