//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalendarDll.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarReccurrence
    {
        public CalendarReccurrence()
        {
            this.CalendarReccurrenceFrequency = new HashSet<CalendarReccurrenceFrequency>();
        }
    
        public int ID { get; set; }
        public Nullable<int> EventID { get; set; }
        public Nullable<int> Count { get; set; }
        public string EvaluationMode { get; set; }
        public Nullable<int> Frequency { get; set; }
        public Nullable<int> Interval { get; set; }
        public Nullable<int> RestristionType { get; set; }
        public Nullable<System.DateTime> Until { get; set; }
        public Nullable<int> FirstDayOfWeek { get; set; }
    
        public virtual ICollection<CalendarReccurrenceFrequency> CalendarReccurrenceFrequency { get; set; }
        public virtual CalendarEvents CalendarEvents { get; set; }
    }
}
