//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalendarDll.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarEventsAttendees
    {
        public int Id { get; set; }
        public int IdEvent { get; set; }
        public string Attendee { get; set; }
        public string Role { get; set; }
        public string Uri { get; set; }
    
        public virtual CalendarEvents CalendarEvents { get; set; }
    }
}
