//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalendarDll.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarProviderAttributes
    {
        public int UserID { get; set; }
        public decimal AdvanceTime { get; set; }
        public decimal MinTime { get; set; }
        public decimal MaxTime { get; set; }
        public decimal BetweenTime { get; set; }
        public bool UseCalendarProgram { get; set; }
        public string CalendarType { get; set; }
        public string CalendarURL { get; set; }
        public string PrivateCalendarToken { get; set; }
    
        public virtual users users { get; set; }
    }
}
