//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalendarDll.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarAvailabilityType
    {
        public CalendarAvailabilityType()
        {
            this.CalendarEvents = new HashSet<CalendarEvents>();
        }
    
        public int CalendarAvailabilityTypeID { get; set; }
        public int LanguageID { get; set; }
        public int CountryID { get; set; }
        public string CalendarAvailabilityTypeName { get; set; }
        public string CalendarAvailabilityTypeDescription { get; set; }
    
        public virtual ICollection<CalendarEvents> CalendarEvents { get; set; }
    }
}
