//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalendarDll.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarReccurrenceFrequency
    {
        public int ID { get; set; }
        public Nullable<int> CalendarReccursiveID { get; set; }
        public Nullable<bool> ByDay { get; set; }
        public Nullable<bool> ByHour { get; set; }
        public Nullable<bool> ByMinute { get; set; }
        public Nullable<bool> ByMonth { get; set; }
        public Nullable<bool> ByMonthDay { get; set; }
        public Nullable<bool> BySecond { get; set; }
        public Nullable<bool> BySetPosition { get; set; }
        public Nullable<bool> ByWeekNo { get; set; }
        public Nullable<bool> ByYearDay { get; set; }
        public Nullable<int> ExtraValue { get; set; }
        public Nullable<int> FrequencyDay { get; set; }
        public Nullable<int> DayOfWeek { get; set; }
    
        public virtual CalendarReccurrence CalendarReccurrence { get; set; }
    }
}
