//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalendarDll.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarProviderAttributes
    {
        public int UserID { get; set; }
        public decimal AdvanceTime { get; set; }
        public decimal MinTime { get; set; }
        public decimal MaxTime { get; set; }
        public decimal BetweenTime { get; set; }
        public bool UseCalendarProgram { get; set; }
        public string CalendarType { get; set; }
        public string CalendarURL { get; set; }
    
        public virtual users users { get; set; }
    }
}
