//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalendarDll.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class postalcode
    {
        public int PostalCodeID { get; set; }
        public string PostalCode1 { get; set; }
        public string City { get; set; }
        public int StateProvinceID { get; set; }
        public int CountryID { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<decimal> TimeZone { get; set; }
        public Nullable<bool> DST { get; set; }
        public string Location { get; set; }
        public string PostalCodeType { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
