//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalendarDll.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class postalcode
    {
        public int PostalCodeID { get; set; }
        public string PostalCode1 { get; set; }
        public string City { get; set; }
        public int StateProvinceID { get; set; }
        public int CountryID { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<decimal> TimeZone { get; set; }
        public Nullable<bool> DST { get; set; }
        public string Location { get; set; }
        public string PostalCodeType { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
