//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalendarDll.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class serviceaddress
    {
        public int AddressID { get; set; }
        public int UserID { get; set; }
        public int PositionID { get; set; }
        public bool ServicesPerformedAtLocation { get; set; }
        public bool TravelFromLocation { get; set; }
        public string ServiceRadiusFromLocation { get; set; }
        public Nullable<int> TransportType { get; set; }
        public bool PreferredAddress { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool Active { get; set; }
    
        public virtual users users { get; set; }
    }
}
