//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalendarDll.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class stateprovince
    {
        public int StateProvinceID { get; set; }
        public string StateProvinceName { get; set; }
        public string StateProvinceCode { get; set; }
        public int CountryID { get; set; }
        public string RegionCode { get; set; }
        public string PostalCodePrefix { get; set; }
    }
}
