//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalendarDll.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class stateprovince
    {
        public int StateProvinceID { get; set; }
        public string StateProvinceName { get; set; }
        public string StateProvinceCode { get; set; }
        public int CountryID { get; set; }
        public string RegionCode { get; set; }
        public string PostalCodePrefix { get; set; }
    }
}
