//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalendarDll.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public users()
        {
            this.serviceaddress = new HashSet<serviceaddress>();
            this.CalendarEvents = new HashSet<CalendarEvents>();
        }
    
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string MiddleIn { get; set; }
        public string LastName { get; set; }
        public string SecondLastName { get; set; }
        public string NickName { get; set; }
        public string PublicBio { get; set; }
        public Nullable<int> GenderID { get; set; }
        public Nullable<int> PreferredLanguageID { get; set; }
        public Nullable<int> PreferredCountryID { get; set; }
        public Nullable<bool> IsProvider { get; set; }
        public Nullable<bool> IsCustomer { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public string Photo { get; set; }
        public string MobilePhone { get; set; }
        public string AlternatePhone { get; set; }
        public string ProviderProfileURL { get; set; }
        public string PersonalizedProviderProfileURL { get; set; }
        public bool SMSBookingCommunication { get; set; }
        public bool PhoneBookingCommunication { get; set; }
        public bool LoconomicsMarketingCampaigns { get; set; }
        public bool ProfileSEOPermission { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool Active { get; set; }
        public bool LoconomicsCommunityCommunication { get; set; }
        public Nullable<bool> IAuthZumigoVerification { get; set; }
        public Nullable<bool> IAuthZumigoLocation { get; set; }
        public bool LoconomicsDBMCampaigns { get; set; }
        public int AccountStatusID { get; set; }
        public bool CoBrandedPartnerPermissions { get; set; }
        public string ProviderWebsiteURL { get; set; }
    
        public virtual CalendarProviderAttributes CalendarProviderAttributes { get; set; }
        public virtual ICollection<serviceaddress> serviceaddress { get; set; }
        public virtual ICollection<CalendarEvents> CalendarEvents { get; set; }
    }
}
