var Lang_Calendar = "Calendar";
var Lang_SimpleWeek = "Simple Week View";
var Lang_SimpleMonth = "Simple Month View";
var Lang_WeeklyCalendarVeiw = " Week Calendar View";
var Lang_SynchExternal = "Synch External Calendars";
var Lang_WeekBeginning = "Week Beginning";
var Lang_AddEventTo = "Add Event To:";
var Lang_ScheduledAndPendingEvents = "Scheduled and Pending";
var Lang_Unscheduled = "Unscheduled";
var Lang_More = "more"
var Lang_Add = "add"
var Lang_End = "End";
var Lang_Start = "Start";
var Lang_Unscheduled = "unscheduled";
var Lang_SynchedEvent = "synched event";
var Lang_Unprocessed = "unprocessed";
var Lang_Reset="Reset";
var Lang_Update = "Update";
var Lang_Free = "Free";
var Lang_Busy = "Busy";