/**
 * 
 * @module viewmodels/CountriesOptions
 * @returns {Array} of country objects with name and id fields suitable for knockout options binding
**/

'use strict';

var countries = [
        [1, 'United States'],
        [2, 'Spain'],
        [3, 'Afghanistan'],
        [4, 'Albania'],
        [5, 'Algeria'],
        [6, 'American Samoa'],
        [7, 'Andorra'],
        [8, 'Angola'],
        [9, 'Anguilla'],
        [10, 'Antarctica'],
        [11, 'Antigua and Barbuda'],
        [12, 'Argentina'],
        [13, 'Armenia'],
        [14, 'Aruba'],
        [15, 'Australia'],
        [16, 'Austria'],
        [17, 'Azerbaijan'],
        [18, 'Bahamas'],
        [19, 'Bahrain'],
        [20, 'Bangladesh'],
        [21, 'Barbados'],
        [22, 'Belarus'],
        [23, 'Belgium'],
        [24, 'Belize'],
        [25, 'Benin'],
        [26, 'Bermuda'],
        [27, 'Bhutan'],
        [28, 'Bolivia'],
        [29, 'Bosnia and Herzegovina'],
        [30, 'Botswana'],
        [31, 'Bouvet Island'],
        [32, 'Brazil'],
        [33, 'British Indian Ocean Territory'],
        [34, 'Brunei Darussalam'],
        [35, 'Bulgaria'],
        [36, 'Burkina Faso'],
        [37, 'Burundi'],
        [38, 'Cambodia'],
        [39, 'Cameroon'],
        [40, 'Canada'],
        [41, 'Cape Verde'],
        [42, 'Cayman Islands'],
        [43, 'Central African Republic'],
        [44, 'Chad'],
        [45, 'Chile'],
        [46, 'China'],
        [47, 'Christmas Island'],
        [48, 'Cocos Keeling) Islands'],
        [49, 'Colombia'],
        [50, 'Comoros'],
        [51, 'Congo'],
        [52, 'Congo Democratic Republic'],
        [53, 'Cook Islands'],
        [54, 'Costa Rica'],
        [55, 'Cote DIvoire'],
        [56, 'Croatia'],
        [57, 'Cuba'],
        [58, 'Cyprus'],
        [59, 'Czech Republic'],
        [60, 'Denmark'],
        [61, 'Djibouti'],
        [62, 'Dominica'],
        [63, 'Dominican Republic'],
        [64, 'Ecuador'],
        [65, 'Egypt'],
        [66, 'El Salvador'],
        [67, 'Equatorial Guinea'],
        [68, 'Eritrea'],
        [69, 'Estonia'],
        [70, 'Ethiopia'],
        [71, 'Falkland Islands Malvinas)'],
        [72, 'Faroe Islands'],
        [73, 'Fiji'],
        [74, 'Finland'],
        [75, 'France'],
        [76, 'French Guiana'],
        [77, 'French Polynesia'],
        [78, 'French Southern Territories'],
        [79, 'Gabon'],
        [80, 'Gambia'],
        [81, 'Georgia'],
        [82, 'Germany'],
        [83, 'Ghana'],
        [84, 'Gibraltar'],
        [85, 'Greece'],
        [86, 'Greenland'],
        [87, 'Grenada'],
        [88, 'Guadeloupe'],
        [89, 'Guam'],
        [90, 'Guatemala'],
        [91, 'Guinea'],
        [92, 'Guinea-Bissau'],
        [93, 'Guyana'],
        [94, 'Haiti'],
        [95, 'Heard and Mcdonald Islands'],
        [96, 'Holy See Vatican City State'],
        [97, 'Honduras'],
        [98, 'Hong Kong'],
        [99, 'Hungary'],
        [100, 'Iceland'],
        [101, 'India'],
        [102, 'Indonesia'],
        [103, 'Iran Islamic Republic of'],
        [104, 'Iraq'],
        [105, 'Ireland'],
        [106, 'Israel'],
        [107, 'Italy'],
        [108, 'Jamaica'],
        [109, 'Japan'],
        [110, 'Jordan'],
        [111, 'Kazakhstan'],
        [112, 'Kenya'],
        [113, 'Kiribati'],
        [114, 'Korea South'],
        [115, 'Korea North'],
        [116, 'Kuwait'],
        [117, 'Kyrgyzstan'],
        [118, 'Laos'],
        [119, 'Latvia'],
        [120, 'Lebanon'],
        [121, 'Lesotho'],
        [122, 'Liberia'],
        [123, 'Libyan Arab Jamahiriya'],
        [124, 'Liechtenstein'],
        [125, 'Lithuania'],
        [126, 'Luxembourg'],
        [127, 'Macao'],
        [128, 'Macedonia'],
        [129, 'Madagascar'],
        [130, 'Malawi'],
        [131, 'Malaysia'],
        [132, 'Maldives'],
        [133, 'Mali'],
        [134, 'Malta'],
        [135, 'Marshall Islands'],
        [136, 'Martinique'],
        [137, 'Mauritania'],
        [138, 'Mauritius'],
        [139, 'Mayotte'],
        [140, 'Mexico'],
        [141, 'Micronesia'],
        [142, 'Moldova'],
        [143, 'Monaco'],
        [144, 'Mongolia'],
        [145, 'Montserrat'],
        [146, 'Morocco'],
        [147, 'Mozambique'],
        [148, 'Myanmar'],
        [149, 'Namibia'],
        [150, 'Nauru'],
        [151, 'Nepal'],
        [152, 'Netherlands'],
        [153, 'Netherlands Antilles'],
        [154, 'New Caledonia'],
        [155, 'New Zealand'],
        [156, 'Nicaragua'],
        [157, 'Niger'],
        [158, 'Nigeria'],
        [159, 'Niue'],
        [160, 'Norfolk Island'],
        [161, 'Northern Mariana Islands'],
        [162, 'Norway'],
        [163, 'Oman'],
        [164, 'Pakistan'],
        [165, 'Palau'],
        [166, 'Palestinian'],
        [167, 'Panama'],
        [168, 'Papua New Guinea'],
        [169, 'Paraguay'],
        [170, 'Peru'],
        [171, 'Philippines'],
        [172, 'Pitcairn'],
        [173, 'Poland'],
        [174, 'Portugal'],
        [175, 'Puerto Rico'],
        [176, 'Qatar'],
        [177, 'Reunion'],
        [178, 'Romania'],
        [179, 'Russian Federation'],
        [180, 'Rwanda'],
        [181, 'Saint Helena'],
        [182, 'Saint Kitts and Nevis'],
        [183, 'Saint Lucia'],
        [184, 'Saint Pierre and Miquelon'],
        [185, 'Saint Vincent/ theGrenadines'],
        [186, 'Samoa'],
        [187, 'San Marino'],
        [188, 'Sao Tome and Principe'],
        [189, 'Saudi Arabia'],
        [190, 'Senegal'],
        [191, 'Serbia and Montenegro'],
        [192, 'Seychelles'],
        [193, 'Sierra Leone'],
        [194, 'Singapore'],
        [195, 'Slovakia'],
        [196, 'Slovenia'],
        [197, 'Solomon Islands'],
        [198, 'Somalia'],
        [199, 'South Africa'],
        [200, 'South Georgia'],
        [201, 'Sri Lanka'],
        [202, 'Sudan'],
        [203, 'Suriname'],
        [204, 'Svalbard and Jan Mayen'],
        [205, 'Swaziland'],
        [206, 'Sweden'],
        [207, 'Switzerland'],
        [208, 'Syrian Arab Republic'],
        [209, 'Taiwan'],
        [210, 'Tajikistan'],
        [211, 'Tanzania'],
        [212, 'Thailand'],
        [213, 'Timor-Leste'],
        [214, 'Togo'],
        [215, 'Tokelau'],
        [216, 'Tonga'],
        [217, 'Trinidad and Tobago'],
        [218, 'Tunisia'],
        [219, 'Turkey'],
        [220, 'Turkmenistan'],
        [221, 'Turks and Caicos Islands'],
        [222, 'Tuvalu'],
        [223, 'Uganda'],
        [224, 'Ukraine'],
        [225, 'United Arab Emirates'],
        [226, 'United Kingdom'],
        [227, 'US Minor Outlying Islands'],
        [228, 'Uruguay'],
        [229, 'Uzbekistan'],
        [230, 'Vanuatu'],
        [231, 'Venezuela'],
        [232, 'Viet Nam'],
        [233, 'Virgin Islands British'],
        [234, 'Virgin Islands U.S.'],
        [235, 'Wallis and Futuna'],
        [236, 'Western Sahara'],
        [237, 'Yemen'],
        [238, 'Zambia'],
        [239, 'Zimbabwe']
    ],
    unitedStates = countries[0];

var option = function(country) {
    return { 'id': country[0], 'name': country[1] };
};

var countriesOptions = function() {
    return countries.map(option);
};

countriesOptions.unitedStates = option(unitedStates);

module.exports = countriesOptions;
