'use strict';
// IMPORTANT: it requires access to DOM with jQuery in order to the COPY LINK to work on browsers
var $ = require('jquery');
var ko = require('knockout');

module.exports = function MarketplaceProfileVM(app) {

    var marketplaceProfile = app.model.marketplaceProfile;

    var profileVersion = marketplaceProfile.newVersion();
    profileVersion.isObsolete.subscribe(function(itIs) {
        if (itIs) {
            // new version from server while editing
            // FUTURE: warn about a new remote version asking
            // confirmation to load them or discard and overwrite them;
            // the same is need on save(), and on server response
            // with a 509:Conflict status (its body must contain the
            // server version).
            // Right now, just overwrite current changes with
            // remote ones:
            profileVersion.pull({ evenIfNewer: true });
        }
    });
    
    // Actual data for the form:
    this.profile = profileVersion.version;

    this.isLoading = marketplaceProfile.isLoading;
    this.isSaving = marketplaceProfile.isSaving;
    this.isLocked = marketplaceProfile.isLocked;

    this.discard = function discard() {
        profileVersion.pull({ evenIfNewer: true });
        this.copyCustomUrlButtonText('Copy');
    }.bind(this);

    this.save = function save() {
        return profileVersion.pushSave();
    };
    
    this.sync = app.model.marketplaceProfile.sync.bind(app.model.marketplaceProfile);
    
    /// Utilities
    // Custom URL
    this.customUrlProtocol = ko.observable('https://');
    this.customUrlDomainPrefix = ko.observable('www.loconomics.com/-');
    /**
        Autogenerated custom URL for the current 'draft' data (being edited by the user)
    **/
    this.customUrlDraft = ko.pureComputed(function() {
        return this.customUrlProtocol() + this.customUrlDomainPrefix() + this.profile.serviceProfessionalProfileUrlSlug();
    }, this);
    // Copy Custom URL
    this.copyCustomUrlButtonText = ko.observable('Copy');
    this.profile.serviceProfessionalProfileUrlSlug.subscribe(function() {
        // On any change, restore copy label
        this.copyCustomUrlButtonText('Copy');
    }.bind(this));
    this.copyCustomUrl = function() {
        var errMsg;
        var url = this.customUrlDraft();
        try {
            // If Cordova Plugin available, use that
            if (window.cordova && window.cordova.plugins && window.cordova.plugins.clipboard) {
                window.cordova.plugins.clipboard.copy(url);
            }
            else {
                // Web standard version: will not work on old Firefox and current Safari (as of 2015-11-26)
                // using setSelectionRange rather than select since seems more compatible (with Safari, but copy does not works
                // there so...maybe for the future I hope :-)
                // IMPORTANT: We need an element with the text and attached to the document DOM, visually hidden to avoid any flicker (if any)
                // but with care to avoid type=hidden or display:none just in case some engines may forbide the copy command on that ones.
                var $code = $('<input type="text" style="position:absolute;left:-90999px;z-index:-9000"/>"');
                $code.appendTo('body').val(url);
                // Copying
                $code
                .select()
                .get(0).setSelectionRange(0, 99999);
                if (!document.execCommand('copy')) {
                    errMsg = 'Impossible to copy text.';
                }
                $code.remove();
            }
        } catch(err) {
            errMsg = 'Impossible to copy text.';
        }
        if (errMsg) {
            app.modals.showError({ error: errMsg });
        }
        else {
            this.copyCustomUrlButtonText('Copied!');
        }
    }.bind(this);
};
