var Lang_Calendar = "Calendario";
var Lang_SimpleWeek = "Ver Semana sencilla";
var Lang_SimpleMonth = "Vista de Mes sencilla";
var Lang_WeeklyCalendarVeiw = " Ver semana Calendario";
var Lang_SynchExternal = "Sincronización externa Calendarios";
var Lang_WeekBeginning = "Semana Del";
var Lang_AddEventTo = "Agregar evento a:";
var Lang_ScheduledAndPendingEvents = "Programados y pendientes";
var Lang_Unscheduled = "No programada";
var Lang_More = "Más"
var Lang_Add = "Añadir"
var Lang_End = "Final";
var Lang_Start = "Comienzo";
var Lang_Unscheduled = "no programada";
var Lang_SynchedEvent = "evento sincronizado";
var Lang_Unprocessed = "sin procesar";
var Lang_Reset = "Reajustar";
var Lang_Update = "Actualizar";