INSERT INTO [postingTemplateQuestion] ([postingTemplateID],[questionID],[legend],[branchLogic],[createdDate],[updatedDate],[modifiedby],[active])
VALUES (1,1,'General Project Info', null, '2018-05-29', '2018-05-29','ils',1)
INSERT INTO [postingTemplateQuestion] ([postingTemplateID],[questionID],[legend],[branchLogic],[createdDate],[updatedDate],[modifiedby],[active])
VALUES (1,2,'General Project Info', null, '2018-05-29', '2018-05-29','ils',1)
INSERT INTO [postingTemplateQuestion] ([postingTemplateID],[questionID],[legend],[branchLogic],[createdDate],[updatedDate],[modifiedby],[active])
VALUES (1,3,'General Project Info', null, '2018-05-29', '2018-05-29','ils',1)
INSERT INTO [postingTemplateQuestion] ([postingTemplateID],[questionID],[legend],[branchLogic],[createdDate],[updatedDate],[modifiedby],[active])
VALUES (1,4,'Project Timeline', null, '2018-05-29', '2018-05-29','ils',1)
INSERT INTO [postingTemplateQuestion] ([postingTemplateID],[questionID],[legend],[branchLogic],[createdDate],[updatedDate],[modifiedby],[active])
VALUES (1,5,'Project Timeline', null, '2018-05-29', '2018-05-29','ils',1)
INSERT INTO [postingTemplateQuestion] ([postingTemplateID],[questionID],[legend],[branchLogic],[createdDate],[updatedDate],[modifiedby],[active])
VALUES (1,6,'Project Timeline', null, '2018-05-29', '2018-05-29','ils',1)
