/** UserLicenseCertification model **/
'use strict';

var Model = require('./Model');
var LicenseCertification = require('./LicenseCertification');

function UserLicenseCertification(values) {

    Model(this);
    
    this.model.defProperties({        
        userLicenseCertificationID: 0,
        userID: 0,
        jobTitleID: 0,
        licenseCertificationID: 0,
        statusID: 0,
        licenseCertificationNumber: '',
        licenseCertificationUrl: '',
        expirationDate: null,
        issueDate: null,
        firstName: null,
        lastName: null,
        middleInitial: null,
        secondLastName: null,
        businessName: null,
        comments: null,
        verifiedBy: null,
        lastVerifiedDate: null,
        submitDate: null, // Autofilled by server
        submittedBy: null,
        status: null,
        statusDescription: null,
                
        licenseCertification: new LicenseCertification(),
        // Additional local data:
        // path to local photo file, unsaved/not-uploaded still.
        localTempFilePath: null,
        localTempPhotoPreviewUrl: null,
        // data of local file, unsaved/not-uploaded still (web file picker support)
        localTempFileData: null,
        // data for generated preview for the localTempFileData (web file picker support; generated by the fileuploader plugin)
        localTempPhotoPreview: null,
        // file name of the picked file, used only locally to preview the name when there is no a preview (is not a photo, like a pdf file)
        localTempFileName: null
    }, values);
    
    this.model.defID(['userID', 'jobTitleID', 'licenseCertificationID']);
}

module.exports = UserLicenseCertification;
