/**
    WorkPhoto Model
**/
'use strict';
var Model = require('./Model');

function WorkPhoto(values) {
    Model(this);
    
    this.model.defProperties({
        workPhotoID: 0,
        userID: 0,
        jobTitleID: 0,
        caption: '',
        fileName: '',
        url: '',
        rankPosition: 0,
        updatedDate: null,
        // Additional local data:
        // path to local file, unsaved/not-uploaded still (native file/camera support)
        localTempFilePath: null,
        // data of local file, unsaved/not-uploaded still (web file picker support)
        localTempFileData: null,
        // data for generated preview for the localTempFileData (web file picker support; generated by the fileuploader plugin)
        localTempPhotoPreview: null
    }, values);
}
module.exports = WorkPhoto;
