/****** Object:  Table [dbo].[CALENDARTimeBlocks]    Script Date: 07/01/2013 12:36:57 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CalendarTimeBlocks](
	[TimeBlockID] [int] NOT NULL,
	[TimeBlock] [time](7) NULL,
 CONSTRAINT [PK_CalendarTimeBlocks] PRIMARY KEY CLUSTERED 
(
	[TimeBlockID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


