INSERT INTO [pricingvariable]
   ([PricingVariableID]
   ,[PositionID]
   ,[ClientTypeID]
   ,[LanguageID]
   ,[CountryID]
   ,[ProviderInputDataRequired]
   ,[CustomerInputDataRequired]
   ,[PricingVariableName]
   ,[ProviderPricingVariableDisplayText]
   ,[CustomerPricingVariableDisplayText]
   ,[ProviderPricingVariableDescription]
   ,[CustomerPricingVariableDescription]
   ,[ProviderDataInputType]
   ,[CustomerDataInputType]
   ,[ProviderDataInputUnit]
   ,[CustomerDataInputUnit]
   ,[ProviderDataValues]
   ,[CustomerDataValues]
   ,[CreatedDate]
   ,[UpdatedDate]
   ,[ModifiedBy]
   ,[Active]
   ,[PricingTypeID]
   ,[PricingSurchargeVariable])
VALUES
   (@PricingVariableID
   ,@PositionID
   ,@ClientTypeID
   ,@LanguageID
   ,@CountryID
   ,@ProviderInputDataRequired
   ,@CustomerInputDataRequired
   ,@PricingVariableName
   ,@ProviderPricingVariableDisplayText
   ,@CustomerPricingVariableDisplayText
   ,@ProviderPricingVariableDescription
   ,@CustomerPricingVariableDescription
   ,@ProviderDataInputType
   ,@CustomerDataInputType
   ,@ProviderDataInputUnit
   ,@CustomerDataInputUnit
   ,@ProviderDataValues
   ,@CustomerDataValues
   ,@CreatedDate
   ,@UpdatedDate
   ,@ModifiedBy
   ,@Active
   ,@PricingTypeID
   ,@PricingSurchargeVariable)
