INSERT INTO [PricingVariableDefinition]  
   ([PricingVariableID]
   ,[LanguageID]
   ,[CountryID]
   ,[PositionID]
   ,[PricingTypeID]
   ,[InternalName]
   ,[IsProviderVariable]
   ,[IsCustomerVariable]
   ,[DataType]
   ,[VariableLabel]
   ,[VariableLabelPopUp]
   ,[VariableNameSingular]
   ,[VariableNamePlural]
   ,[NumberIncludedLabel]
   ,[NumberIncludedLabelPopUp]
   ,[HourlySurchargeLabel]
   ,[MinNumberAllowedLabel]
   ,[MinNumberAllowedLabelPopUp]
   ,[MaxNumberAllowedLabel]
   ,[MaxNumberAllowedLabelPopUp]
   ,[CalculateWithVariableID]
   ,[Active]
   ,[CreatedDate]
   ,[UpdatedDate]
   ,[ModifiedBy]
   ,[MinMaxValuesList])
VALUES
   (@PricingVariableID
   ,@LanguageID
   ,@CountryID
   ,@PositionID
   ,@PricingTypeID
   ,@InternalName
   ,@IsProviderVariable
   ,@IsCustomerVariable
   ,@DataType
   ,@VariableLabel
   ,@VariableLabelPopUp
   ,@VariableNameSingular
   ,@VariableNamePlural
   ,@NumberIncludedLabel
   ,@NumberIncludedLabelPopUp
   ,@HourlySurchargeLabel
   ,@MinNumberAllowedLabel
   ,@MinNumberAllowedLabelPopUp
   ,@MaxNumberAllowedLabel
   ,@MaxNumberAllowedLabelPopUp
   ,@CalculateWithVariableID
   ,@Active
   ,@CreatedDate
   ,@UpdatedDate
   ,@ModifiedBy
   ,@MinMaxValuesList)