INSERT INTO [alert]
   ([AlertID]
   ,[LanguageID]
   ,[CountryID]
   ,[AlertName]
   ,[CreatedDate]
   ,[UpdatedDate]
   ,[ModifiedBy]
   ,[Active]
   ,[Required]
   ,[PositionSpecific]
   ,[DisplayRank]
   ,[ProviderAlert]
   ,[CustomerAlert]
   ,[bookMeButtonRequired])
VALUES
   (@AlertID
   ,@LanguageID
   ,@CountryID
   ,@AlertName
   ,@CreatedDate
   ,@UpdatedDate
   ,@ModifiedBy
   ,@Active
   ,@Required
   ,@PositionSpecific
   ,@DisplayRank
   ,@ProviderAlert
   ,@CustomerAlert
   ,@bookMeButtonRequired)
