INSERT INTO [PricingVariableDefinition]
   ([PricingVariableID]
   ,[LanguageID]
   ,[CountryID]
   ,[PositionID]
   ,[PricingTypeID]
   ,[InternalName]
   ,[IsProviderVariable]
   ,[IsCustomerVariable]
   ,[DataType]
   ,[VariableLabel]
   ,[VariableLabelPopUp]
   ,[VariableNameSingular]
   ,[VariableNamePlural]
   ,[NumberIncludedLabel]
   ,[NumberIncludedLabelPopup]
   ,[CalculateWithVariableID]
   ,[CreatedDate]
   ,[UpdatedDate]
   ,[ModifiedBy]
   ,[Active])
VALUES
   (@PricingVariableID
   ,@LanguageID
   ,@CountryID
   ,@PositionID
   ,@PricingTypeID
   ,@InternalName
   ,@IsProviderVariable
   ,@IsCustomerVariable
   ,@DataType
   ,@VariableLabel
   ,@VariableLabelPopUp
   ,@VariableNameSingular
   ,@VariableNamePlural
   ,@NumberIncludedLabel
   ,@NumberIncludedLabelPopup
   ,@CalculateWithVariableID
   ,@CreatedDate
   ,@UpdatedDate
   ,@ModifiedBy
   ,@Active)