INSERT INTO [positionratings]
   ([PositionID]
   ,[LanguageID]
   ,[CountryID]
   ,[Rating1]
   ,[Rating2]
   ,[Rating3]
   ,[Rating4]
   ,[Rating1FormDescription]
   ,[Rating2FormDescription]
   ,[Rating3FormDescription]
   ,[Rating4FormDescription]
   ,[Rating1ProfileDescription]
   ,[Rating2ProfileDescription]
   ,[Rating3ProfileDescription]
   ,[Rating4ProfileDescription]
   ,[CreatedDate]
   ,[UpdatedDate]
   ,[ModifiedBy])
VALUES
   (@PositionID
   ,@LanguageID
   ,@CountryID
   ,@Rating1
   ,@Rating2
   ,@Rating3
   ,@Rating4
   ,@Rating1FormDescription
   ,@Rating2FormDescription
   ,@Rating3FormDescription
   ,@Rating4FormDescription
   ,@Rating1ProfileDescription
   ,@Rating2ProfileDescription
   ,@Rating3ProfileDescription
   ,@Rating4ProfileDescription
   ,@CreatedDate
   ,@UpdatedDate
   ,@ModifiedBy)
