INSERT INTO [serviceattributecategory]
       ([ServiceAttributeCategoryID]
       ,[LanguageID]
       ,[CountryID]
       ,[ServiceAttributeCategory]
       ,[CreateDate]
       ,[UpdatedDate]
       ,[ModifiedBy]
       ,[Active]
       ,[SourceID]
       ,[PricingOptionCategory]
       ,[ServiceAttributeCategoryDescription]
       ,[RequiredInput]
       ,[SideBarCategory]
       ,[EligibleForPackages]
       ,[DisplayRank]
       ,[PositionReference]
       ,[BookingPathSelection])
 VALUES
       (@ServiceAttributeCategoryID
       ,@LanguageID
       ,@CountryID
       ,@ServiceAttributeCategory
       ,@CreateDate
       ,@UpdatedDate
       ,@ModifiedBy
       ,@Active
       ,@SourceID
       ,@PricingOptionCategory
       ,@ServiceAttributeCategoryDescription
       ,@RequiredInput
       ,@SideBarCategory
       ,@EligibleForPackages
       ,@DisplayRank
       ,@PositionReference
       ,@BookingPathSelection)