INSERT INTO [positions]
   ([PositionID]
   ,[LanguageID]
   ,[CountryID]
   ,[PositionSingular]
   ,[PositionPlural]
   ,[Aliases]
   ,[PositionDescription]
   ,[CreatedDate]
   ,[UpdatedDate]
   ,[ModifiedBy]
   ,[GovID]
   ,[GovPosition]
   ,[GovPositionDescription]
   ,[Active]
   ,[DisplayRank]
   ,[PositionSearchDescription]
   ,[AttributesComplete]
   ,[StarRatingsComplete]
   ,[PricingTypeComplete])
VALUES
   (@PositionID
   ,@LanguageID
   ,@CountryID
   ,@PositionSingular
   ,@PositionPlural
   ,@Aliases
   ,@PositionDescription
   ,@CreatedDate
   ,@UpdatedDate
   ,@ModifiedBy
   ,@GovID
   ,@GovPosition
   ,@GovPositionDescription
   ,@Active
   ,@DisplayRank
   ,@PositionSearchDescription
   ,@AttributesComplete
   ,@StarRatingsComplete
   ,@PricingTypeComplete)