INSERT INTO [country]
    ([CountryID]
    ,[LanguageID]
    ,[CountryName]
    ,[CountryCode]
    ,[CountryCodeAlpha2]
    ,[CountryCallingCode]
    ,[CreatedDate]
    ,[UpdatedDate]
    ,[ModifiedBy]
    ,[Active]
    ,[numcode])
VALUES
    (@CountryID
    ,@LanguageID
    ,@CountryName
    ,@CountryCode
    ,@CountryCodeAlpha2
    ,@CountryCallingCode
    ,@CreatedDate
    ,@UpdatedDate
    ,@ModifiedBy
    ,@Active
    ,@numcode)
