INSERT INTO [alert]
   ([AlertID]
   ,[LanguageID]
   ,[CountryID]
   ,[AlertName]
   ,[AlertHeadlineDisplay]
   ,[AlertTextDisplay]
   ,[AlertDescription]
   ,[AlertEmailText]
   ,[ProviderProfileCompletePoints]
   ,[CustomerProfileCompletePoints]
   ,[CreatedDate]
   ,[UpdatedDate]
   ,[ModifiedBy]
   ,[Active]
   ,[AlertPageURL]
   ,[Required]
   ,[PositionSpecific]
   ,[DisplayRank]
   ,[ProviderAlert]
   ,[CustomerAlert]
   ,[bookMeButtonRequired])
VALUES
   (@AlertID
   ,@LanguageID
   ,@CountryID
   ,@AlertName
   ,@AlertHeadlineDisplay
   ,@AlertTextDisplay
   ,@AlertDescription
   ,@AlertEmailText
   ,@ProviderProfileCompletePoints
   ,@CustomerProfileCompletePoints
   ,@CreatedDate
   ,@UpdatedDate
   ,@ModifiedBy
   ,@Active
   ,@AlertPageURL
   ,@Required
   ,@PositionSpecific
   ,@DisplayRank
   ,@ProviderAlert
   ,@CustomerAlert
   ,@bookMeButtonRequired)
