INSERT INTO [institution]
           ([InstitutionID]
           ,[DeptOfEdInstitutionID]
           ,[InstitutionName]
           ,[InstitutionAddress]
           ,[InstitutionCity]
           ,[InstitutionState]
           ,[StateProvinceID]
           ,[InstitutionZip]
           ,[InstitutionPhone]
           ,[InstitutionOPEID]
           ,[InstitutionIPEDSUnitID]
           ,[InstitutionURL]
           ,[CountryID]
           ,[CreatedDate]
           ,[UpdatedDate]
           ,[ModifiedBy])
     VALUES
           (@InstitutionID
           ,@DeptOfEdInstitutionID
           ,@InstitutionName
           ,@InstitutionAddress
           ,@InstitutionCity
           ,@InstitutionState
           ,@StateProvinceID
           ,@InstitutionZip
           ,@InstitutionPhone
           ,@InstitutionOPEID
           ,@InstitutionIPEDSUnitID
           ,@InstitutionURL
           ,@CountryID
           ,@CreatedDate
           ,@UpdatedDate
           ,@ModifiedBy)
