INSERT INTO [servicecategorypositionattribute]
   ([PositionID]
   ,[ServiceAttributeCategoryID]
   ,[ServiceAttributeID]
   ,[LanguageID]
   ,[CountryID]
   ,[CreateDate]
   ,[UpdatedDate]
   ,[ModifiedBy]
   ,[Active])
VALUES
   (@PositionID
   ,@ServiceAttributeCategoryID
   ,@ServiceAttributeID
   ,@LanguageID
   ,@CountryID
   ,@CreateDate
   ,@UpdatedDate
   ,@ModifiedBy
   ,@Active)