CREATE TABLE dbo.Solution
(SolutionID int NOT NULL,
LanguageID int NOT NULL,
CountryID int NOT NULL,
Name nvarchar(100) NOT NULL,
Aliases nvarchar(300),
ShortClientDescription nvarchar(100),
LongClientDescription nvarchar(300),
ShortProfessionalDescription nvarchar(100),
LongProfessionalDescription nvarchar(300),
CredentialCheckRequired bit DEFAULT 0 NOT NULL,
BackgroundCheckRequired bit DEFAULT 0 NOT NULL,
IsHIPAA bit DEFAULT 0 NOT NULL,
TaxActivityID int,
PostingTemplateID int,
SmallImage nvarchar(255),
BannerImage nvarchar(255),
CreatedDate datetimeoffset NOT NULL,
UpdatedDate datetimeoffset NOT NULL,
ModifiedBy nvarchar(4) DEFAULT 'sys' NOT NULL,
Active bit DEFAULT 1 NOT NULL,
PRIMARY KEY (SolutionID,LanguageID, CountryID));