INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (1,153,1,1,'Deep tissue','Deep tissue massage is designed to relieve severe tension in the muscle and the connective tissue or fascia. This type of massage focuses on the muscles located below the surface of the top muscles. Deep tissue massage is often recommended for individuals who experience consistent pain, are involved in heavy physical activity (such as athletes), and patients who have sustained physical injury. It is not uncommon for receivers of deep tissue massage to have their pain replaced with a new muscle ache for a day or two. Deep tissue work varies greatly.

The term deep tissue is often misused to identify a massage that is performed with sustained deep pressure. Deep tissue massage is a separate category of massage therapy, used to treat particular muscular-skeletal disorders and complaints and employs a dedicated set of techniques and strokes to achieve a measure of relief. It should not be confused with deep pressure massage, which is one that is performed with sustained strong, occasionally intense pressure throughout an entire full-body session, and that is not performed to address a specific complaint. Deep tissue massage is applied to both the superficial and deep layers of muscles, fascia, and other structures. The sessions are often quite intense as a result of the deliberate, focused work. When a client asks for a massage and uses the term deep tissue, more often than not he or she is seeking to receive a full-body session with sustained deep pressure throughout. If a practitioner employs deep tissue techniques on the entire body in one session, it would be next to impossible to perform; it might lead to injury or localized muscle and nerve trauma, thereby rendering the session counterproductive.',1000,'2018-03-05 11:05:00.000','2018-03-05 00:00:00.0000000 +00:00','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (2,153,1,1,'Swedish','Swedish massage uses five styles of long, flowing strokes to massage. The five basic strokes are effleurage (sliding or gliding), petrissage (kneading), tapotement (rhythmic tapping), friction (cross fiber) and vibration/shaking. Swedish massage has shown to be helpful in reducing pain, joint stiffness, and improving function in patients with osteoarthritis of the knee over a period of eight weeks. It has also been shown to be helpful in individuals with poor circulation. The term "Swedish" massage is actually only recognized in English or Dutch speaking countries. Elsewhere the style is referred to as "classic massage".',990,'2018-03-06 11:05:00.000','2018-03-05 00:00:00.0000000 +00:01','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (3,153,1,1,'Myofascial release','Myofascial release refers to the manual massage technique for stretching the fascia and releasing bonds between fascia, integument, and muscles with the goal of eliminating pain, increasing range of motion and equilibrioception. Myofascial release usually involves applying shear compression or tension in various directions, or by skin rolling.',980,'2018-03-07 11:05:00.000','2018-03-05 00:00:00.0000000 +00:02','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (4,153,1,1,'Acupressure','Acupressure (a portmanteau of "acupuncture" and "pressure") is a traditional Chinese medicine (TCM) technique derived from acupuncture. With acupressure physical pressure is applied to acupuncture points by the hand, elbow, or with various devices.',970,'2018-03-08 11:05:00.000','2018-03-05 00:00:00.0000000 +00:03','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (5,153,1,1,'Trigger point release','Sometimes confused with pressure point massage, this involves deactivating trigger points that may cause local pain or refer pain and other sensations, such as headaches, in other parts of the body. Manual pressure, vibration, injection, or other treatment is applied to these points to relieve myofascial pain. Trigger points were first discovered and mapped by Janet G. Travell (president Kennedy''''s physician) and David Simons. These points relate to dysfunction in the myoneural junction, also called neuromuscular junction (NMJ), in muscle, and therefore this modality is different from reflexology, acupressure and pressure point massage.',960,'2018-03-09 11:05:00.000','2018-03-05 00:00:00.0000000 +00:04','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (6,153,1,1,'Sports','',950,'2018-03-10 11:05:00.000','2018-03-05 00:00:00.0000000 +00:05','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (7,153,1,1,'Pre/Perinatal','',940,'2018-03-11 11:05:00.000','2018-03-05 00:00:00.0000000 +00:06','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (8,153,1,1,'Reflexology','Reflexology is based on the principle that there are reflexes in the hands and feet that relate to every organ, gland, and system of the body.',930,'2018-03-12 11:05:00.000','2018-03-05 00:00:00.0000000 +00:07','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (9,153,1,1,'Shiatsu','Shiatsu is a Japanese therapy that uses pressure applied with thumbs, fingers and palms to the same energy meridians as acupressure and incorporates stretching. It also uses techniques such as rolling, brushing, vibrating, grasping and, in one particular technique developed by Suzuki Yamamoto, pressure is applied with the feet on the person''s back, legs and feet.',920,'2018-03-13 11:05:00.000','2018-03-05 00:00:00.0000000 +00:08','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (10,153,1,1,'Thai','Known in Thailand as Nuat phaen boran, IPA, meaning "ancient/traditional massage", Thai massage originated in India and is based on ayurveda and yoga. The technique combines massage with yoga-like positions during the course of the massage; the northern style emphasizes stretching while the southern style emphasizes acupressure.',910,'2018-03-14 11:05:00.000','2018-03-05 00:00:00.0000000 +00:09','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (11,153,1,1,'Lymphatic drainage','Massage technique used to gently work and stimulate the lymphatic system, to assist in reduction of localised swelling.',900,'2018-03-15 11:05:00.000','2018-03-05 00:00:00.0000000 +00:10','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (12,153,1,1,'Active Release Techniques (ART)','ART has been developed, refined, and patented by P. Michael Leahy, DC, CCSP. Dr. Leahy noticed that his patients'' symptoms seemed to be related to changes in their soft tissue that could be felt by hand. By observing how muscles, fascia, tendons, ligaments and nerves responded to different types of work, Dr. Leahy was able to consistently resolve over 90% of his patients'' problems. He now teaches and certifies health care providers all over the world to use ART. [http://www.activerelease.com/what_patients.asp]',890,'2018-03-16 11:05:00.000','2018-03-05 00:00:00.0000000 +00:11','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (13,153,1,1,'Tui-na','The practitioner may brush, knead, roll/press, and rub the areas between each of the joints, known as the eight gates, to attempt to open the body''s defensive (wei) chi and get the energy moving in the meridians and the muscles. The practitioner can then use range of motion, traction, and massage, with the stimulation of acupressure points. These techniques are claimed to aid in the treatment of both acute and chronic musculoskeletal conditions, as well as many non-musculoskeletal conditions. [http://en.wikipedia.org/wiki/Tui_na]',880,'2018-03-17 11:05:00.000','2018-03-05 00:00:00.0000000 +00:12','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (14,153,1,1,'Structural integration','Structural integration''''s aim is to unwind the strain patterns residing in your body''''s myofascial system, restoring it to its natural balance, alignment, length, and ease. This is accomplished by deep, slow, fascial and myofascial manipulation, coupled with movement re-education. Various brands of Structural Integration are Kinesis Myofascial Integration and rolfing.',870,'2018-03-18 11:05:00.000','2018-03-05 00:00:00.0000000 +00:13','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (15,153,1,1,'Balinese','Balinese massage techniques are gentle and aim to make the patient feel relaxed and calm throughout. The techniques include skin folding, kneading, stroking,and other techniques. The massage therapist applies aromatheraphy oil throughout the massage. A patient''''s blood, oxygen and energy flow is said to increase as a result of the treatment.[citation needed] Balinese hot stones are an option.',860,'2018-03-19 11:05:00.000','2018-03-05 00:00:00.0000000 +00:14','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (16,153,1,1,'Barefoot deep tissue','Barefoot deep tissue, also known as barefoot compressive deep tissue, or barefoot sports massage, is a blend of Eastern barefoot techniques, such as barefoot Shiatsu massage, coupled with a Western manual medicine, encompassing deep tissue, myofascial release, trigger point therapy, transverse friction, compression, tension, shear, PNF, stretching, as well as parasympathetic response, on clothed clients using no oil. Dara Torres, 41-year-old Olympian, received barefoot compression massage on a daily basis in her training program.[20]

This modality typically uses the heel, sesamoid, arch and/or whole plantar surface of foot, and offers large compression, tension and shear forces with less pressure than elbow or thumb, and is ideal for large muscles, such as in thigh, or for long-duration upper trapezius compressions.[21] The unclothed cousins of this modality are Keralite, Yumeiho, Barefoot Lomi Lomi, Fijian Barefoot, Chavutti Thirummal.

Ashiatsu Oriental Bar Therapy, which is a form of barefoot effleurage, combines western science and contemporary American ingenuity, for therapists who specialize in deep tissue work using Swedish techniques performed by the massage therapist''''s feet.',850,'2018-03-20 11:05:00.000','2018-03-05 00:00:00.0000000 +00:15','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (17,153,1,1,'Craniosacral','The therapist lightly palpates the patient''s body, and focuses intently on the communicated movements. A practitioner''s feeling of being in tune with a patient is described as entrainment. Patients often report feelings of deep relaxation during and after the treatment session, and may feel light-headed. This is popularly associated with increases in endorphins, but research shows the effects may actually be brought about by the endocannabinoid system. [http://en.wikipedia.org/wiki/Craniosacral_therapy]',840,'2018-03-21 11:05:00.000','2018-03-05 00:00:00.0000000 +00:16','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (18,153,1,1,'Stone','A stone massage uses cold or water-heated stones to apply pressure and heat to the body. Stones coated in oil can also be used by the therapist delivering various massaging strokes. The hot stones used are commonly Basalt stones (or lava rocks) which over time have become extremely polished and smooth. As the stones are placed along the recipient s back, they help to retain heat which then deeply penetrates into the muscles, releasing tension.',830,'2018-03-22 11:05:00.000','2018-03-05 00:00:00.0000000 +00:17','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (19,153,1,1,'Postural integration (PI)','Postural Integration (PI) is a process-oriented bodywork combining deep tissue massage with breathwork, body movement and awareness as well as emotional expression.',820,'2018-03-23 11:05:00.000','2018-03-05 00:00:00.0000000 +00:18','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (20,153,1,1,'Therapeutic','',810,'2018-03-24 11:05:00.000','2018-03-05 00:00:00.0000000 +00:19','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (21,153,1,1,'Ayurvedic','Ayurveda is a natural health care system originating in India that incorporates massage, yoga, meditation and herbal remedies. Ayurvedic massage, also known as Abhyangha is usually performed by one or two therapists using a heated blend of herbal oils based on the ayurvedic system of humors.',800,'2018-03-25 11:05:00.000','2018-03-05 00:00:00.0000000 +00:20','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (22,153,1,1,'Anma','Anma is a traditional Japanese massage involving kneading and deep tissue work.',790,'2018-03-26 11:05:00.000','2018-03-05 00:00:00.0000000 +00:21','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (23,153,1,1,'Esalen','Esalen Massage was developed by Charlotte Selver and works with gentle rocking of the body, passive joint exercises and deep structural work on the muscles and joints, together with an "energetic balancing" of the body.',780,'2018-03-27 11:05:00.000','2018-03-05 00:00:00.0000000 +00:22','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (24,153,1,1,'Orthopedic','',770,'2018-03-28 11:05:00.000','2018-03-05 00:00:00.0000000 +00:23','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (25,153,1,1,'Visceral manipulation','One form is Mayan abdominal massage which is practiced in many countries in Latin America. This type of massage was developed by Elijio Panti of Belize and brought to the United States by Rosita Arvigo. Even though Panti was a respected and well known user of Mayan massage, he did not develop this modality. "Mayan Massage" techniques have been used since before the Spanish conquest and is still practiced today by many Sobadores or Hueseros (Bonesetters).',760,'2018-03-29 11:05:00.000','2018-03-05 00:00:00.0000000 +00:24','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (26,153,1,1,'Structural Foot Balancing','',750,'2018-03-30 11:05:00.000','2018-03-05 00:00:00.0000000 +00:25','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (27,153,1,1,'Vibrational Healing Massage Therapy','',740,'2018-03-31 11:05:00.000','2018-03-05 00:00:00.0000000 +00:26','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (28,153,1,1,'Myomassology','An integration of techniques including basic Swedish massage, aromatherapy, reflexology, shiatsu, energy balancing, and craniosacral therapy along with other modalities in conjunction with instruction in nutrition, meditation and yoga. The term Myomassology was coined by Irene Gauthier to describe her combined work of Swedish massage, craniosacral therapy, reflexology and body mechanics.',730,'2018-04-01 11:05:00.000','2018-03-05 00:00:00.0000000 +00:27','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (29,153,1,1,'Traditional Chinese','Two types of traditional Chinese massage exist - Tui na which focuses on pushing, stretching and kneading the muscle and Zhi Ya which focuses on pinching and pressing atacupressure points. Both are based on principles from Traditional Chinese Medicine. Though in the Western countries Tui Na is viewed as massage, it is not. Massage of Chinese Medicine is known as Anmo, which is the foundation of Japan''''s Anma.

Tui Na is Chinese Medicine''''s Physio-Therapy. Utilized for medical purposes instead of relaxation, Tui Na works to correct the patient''''s problems, from musculoskeletal conditions, to diseases, cancers and even minor and major headaches.

Within the foundation of Tui Na, Traditional Chinese Medicine principles are followed, from Meridian Applications to Herbal Formulas, Qigong Therapy and heated herbal application (Moxa). Technique applications such as friction and vibration are used as well.',720,'2018-04-02 11:05:00.000','2018-03-05 00:00:00.0000000 +00:28','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (30,153,1,1,'Trager approach','The Trager approach combines movement, massage and education.',710,'2018-04-03 11:05:00.000','2018-03-05 00:00:00.0000000 +00:29','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (31,153,1,1,'Watsu','Watsu is the combination of hydrotherapy and shiatsu developed by Harold Dull. The work is done in skin temperature water with both the therapist and practitioner in the water, usually a pool which is between 3.5 ft to 4 ft (100-120 cm) deep. The work entails much movement in the water and practitioners believe that it incorporates the activation of the energy lines derived from shiatsu.',700,'2018-04-04 11:05:00.000','2018-03-05 00:00:00.0000000 +00:30','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (32,153,1,1,'Transformational Bodywork','',690,'2018-04-05 11:05:00.000','2018-03-05 00:00:00.0000000 +00:31','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (33,153,1,1,'Breathwork','',680,'2018-04-06 11:05:00.000','2018-03-05 00:00:00.0000000 +00:32','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (34,153,1,1,'Clinical','',670,'2018-04-07 11:05:00.000','2018-03-05 00:00:00.0000000 +00:33','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (35,153,1,1,'Medical','',660,'2018-04-08 11:05:00.000','2018-03-05 00:00:00.0000000 +00:34','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (36,153,1,1,'Occupational','',650,'2018-04-09 11:05:00.000','2018-03-05 00:00:00.0000000 +00:35','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (37,153,1,1,'Jop Sen Thai Massage','',640,'2018-04-10 11:05:00.000','2018-03-05 00:00:00.0000000 +00:36','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (38,153,1,1,'Lomi Lomi','Lomilomi is the traditional massage of Hawaii. As an indigenous practice, it varies by island and by family. The word lomilomi also is used for massage in Samoa and East Futuna. In Samoa, it is also known as lolomi and milimili. In East Futuna, it is also called milimili, fakasolosolo, amoamo, lusilusi, kinikini, faiua. The Maori call it roromi and mirimiri. In Tonga massage is fotofota, tolotolo, andamoamo. In Tahiti it is rumirumi. On Nanumea in Tuvalu, massage is known as popo, pressure application is kukumi, and heat application is tutu.',630,'2018-04-11 11:05:00.000','2018-03-05 00:00:00.0000000 +00:37','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (39,153,1,1,'Meso-American','In Meso-America as in other areas of the world an indigenous form of soft tissue and structural massage has developed. Today this art survives thanks to the many Sobadoras/es or Hueseros/as that have handed-down these techniques via oral tradition.',620,'2018-04-12 11:05:00.000','2018-03-05 00:00:00.0000000 +00:38','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (40,153,1,1,'Breema','Breema bodywork is performed on the floor with the recipient fully clothed. It consists of rhythmical and gentle leans and stretches.',610,'2018-04-13 11:05:00.000','2018-03-05 00:00:00.0000000 +00:39','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (41,153,1,1,'Champissage','Champissage is a massage technique focusing on the head, neck and face that is believed to balance the chakras.',600,'2018-04-14 11:05:00.000','2018-03-05 00:00:00.0000000 +00:40','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (42,153,1,1,'Bowen therapy','Bowen technique involves a rolling movement over fascia, muscles, ligaments, tendons and joints. It is said not to involve deep or prolonged contact with muscle tissues as in most kinds of massage, but claims to relieve muscle tensions and strains and to restore normal lymphatic flow. Because this technique is so gentle, so Bowen Therapy can be suitable for newborn baby to elderly. It is based on practices developed by Australian Tom Bowen.',590,'2018-04-15 11:05:00.000','2018-03-05 00:00:00.0000000 +00:41','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (43,153,1,1,'Hilot','Hilot is a traditional healing technique from the Philippines that also includes massage techniques. The massage techniques relax stressed muscles. Hilot also includes joint manipulations to help relax stressed muscles.

Hilot encompasses a wide variety of techniques beyond the treatment of stressed muscles. Hilot can be used to reset sprained joints, diagnose and treat musculoligamentous and musculoskeletal ailments, and even to aid in giving birth and to induce abortion.

Dislocated joints can also be reset by hilot after an X-ray has been done on affected body parts and medical experts advised that the same body parts are safe to be massaged.

After giving birth, hilot can be done on the mother and the baby born of normal delivery for 10 consecutive days so that they may recover easily. Hilot should not be done on mothers who deliver via caesarian section.

Hilot also uses banana leaves and herbs for enhanced efficacy.',580,'2018-04-16 11:05:00.000','2018-03-05 00:00:00.0000000 +00:42','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (44,44,1,1,'Routine Cleaning','',1000,'2018-04-17 11:05:00.000','2018-03-05 00:00:00.0000000 +00:43','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (45,44,1,1,'Deep Cleaning','',990,'2018-04-18 11:05:00.000','2018-03-05 00:00:00.0000000 +00:44','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (46,44,1,1,'Move-out Cleaning','',980,'2018-04-19 11:05:00.000','2018-03-05 00:00:00.0000000 +00:45','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (47,44,1,1,'Move-in Cleaning','',970,'2018-04-20 11:05:00.000','2018-03-05 00:00:00.0000000 +00:46','jd',1,1);
INSERT INTO dbo.Specialization (SpecializationID,SolutionID,LanguageID,CountryID,Name,Description,DisplayRank,CreatedDate,UpdatedDate,CreatedBy,Approved,Active) VALUES (48,44,1,1,'Post-party cleaning','',960,'2018-04-21 11:05:00.000','2018-03-05 00:00:00.0000000 +00:47','jd',1,1);
